---
- name: install software
  yum: name='nginx' state=latest

- name: create dir
  file: path=/etc/nginx/sites-enabled state=directory

- name: create dir
  file: path=/etc/nginx/ssl state=directory

- name: create dir
  file: path=/etc/nginx/logs state=directory

- name: nginx config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: enable nginx
  service: name=nginx state=started enabled=yes

#- name: Copy nginx configuration
#  template: src=front.conf.j2 dest=/etc/nginx/sites-enabled/{{ front_server_name }}.conf
#  #notify: reload nginx
#  tags: front
#
#- name: Copy nginx configuration
#  template: src=ruby.conf.j2 dest=/etc/nginx/sites-enabled/{{ ruby_server_name }}.conf
#  #notify: reload nginx
#  tags: ruby
#
#- name: Copy nginx configuration
#  template: src=tomcat.conf.j2 dest=/etc/nginx/sites-enabled/{{ tomcat_server_name }}.conf
#  #notify: reload nginx
#  tags: tomcat
#
#- name: Copy nginx configuration
#  template: src=common.conf.j2 dest=/etc/nginx/sites-enabled/{{ server_name }}.conf
#  notify: reload nginx
#  tags: common
