---
- name: download nvm
  remote_user: atyun
  script: install_nvm.sh >> download_log.txt
  args:
   creates: download.txt

- name: source .bashrc
  remote_user: atyun
  shell: source /home/{{ local_user }}/.bashrc
  args:
    executable: /bin/bash

- name: install node
  remote_user: atyun
  shell: source /home/{{ local_user }}/.bashrc && nvm install {{ node }}
  args:
    executable: /bin/bash
  tags: node

#- name: install pm2
#  remote_user: {{ local_user }}
#  shell: npm install pm2 -g
#  tags: pm2
