---

- name: copy get-pip.py
  copy: src=get-pip.py dest=/root/get-pip.py

- name: install pip
  shell: python get-pip.py

- name: install sdk
  shell: pip install oassdk

- name: config  oascmd
  shell: oascmd.py config --host=cn-hangzhou.oas-internal.aliyuncs.com -i <access> -k <key>
  become: true
  become_user: postgres

- name: create back dir
  file: path=/home/postgres/pgdata/back state=directory mode=0755 owner=postgres group=postgres

- name: create data dir
  file: path=/home/postgres/pgdata/back/{{ item }} state=directory mode=0755 owner=postgres group=postgres
  with_items:
   - xxxxx
   - yyyyy

- name: copy back_web.py
  copy: src=back_web.py dest=/home/postgres/pgdata/back/back_web.py owner=postgres group=postgres mode=0777

- name: copy back_web.sh
  copy: src=back_web.sh dest=/home/postgres/pgdata/back/back_web.sh owner=postgres group=postgres mode=0777

- name: update crontab
  shell: echo "0 1 * * * /home/postgres/pgdata/back/back_web.sh > /dev/null" >> /var/spool/cron/postgres
