---
- name: install epel
  yum: name=epel-release
- name: install dependents
  yum: name={{ item }}
  with_items:
   - libselinux-python
   - htop
   - iftop
   - lvm2
   - vim
   - autojump
   - wget
   - lsof
   - gcc
   - curl
   - zip
   - unzip
   - tmux
   - telnet
   - python-devel
   - git
   - httpd
   - ruby-json
   - facter

- name: user add
  user: name={{ app_user }} password={{ 'your_password' | password_hash('sha512') }}

- name: install nginx repo
  copy: src=nginx.repo   dest=/etc/yum.repos.d/nginx.repo

- name: copy qalias.sh
  copy: src=qalias.sh dest=/usr/local/bin/qalias.sh mode=0777

- selinux: state=disabled

- name: copy ssh config
  copy: src=sshd_config dest=/etc/ssh/sshd_config
  #notify: restart sshd
