---
- name: install epel
  yum: name=epel-release
- name: install dependents
  yum: name={{ item }}
  with_items:
   - libselinux-python
   - htop
   - iftop
   - lvm2
   - vim
   - autojump
   - wget
   - lsof
   - gcc
   - curl
   - zip
   - unzip
   - tmux
   - telnet
   - python-devel
   - git
   - httpd
   - fontconfig
   - google-crosextra-carlito-fonts.noarch
   - google-crosextra-caladea-fonts.noarch
   - jemalloc-devel

- name: user add
  user: name={{ common_user }} password={{ '' | password_hash('sha512') }}

- name: generate ssh key
  user: name={{ app_user }} generate_ssh_key=yes

- name: ssh-copy
  authorized_key: user={{ local_user }} key="{{ lookup('file', '/Users/xxxx/.ssh/id_rsa.pub') }}"
  tags:
    - sshkey

- name: change_lang
  shell: localectl set-locale LANG=zh_CN.utf8

- name: install nginx repo
  copy: src=nginx.repo   dest=/etc/yum.repos.d/nginx.repo

- selinux: state=disabled

- name: copy ssh config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  tags: ssh
  notify: restart sshd

- name: create pv
  lvg: vg=data pvs=/dev/vdb

- name: create lv
  lvol: vg=data lv=data size={{ volume}}

- name: Create a ext4 filesystem
  filesystem:
    fstype: ext4
    dev: /dev/mapper/data-data

- name: mount disk
  mount:
    path: /www
    src: /dev/mapper/data-data
    fstype: ext4
    state: mounted