---
- name: add ip to pg_ctl.conf
  hosts: database
  remote_user: postgres
  vars:
    ip: xxx
    database: xxx
    user: xxx
  tasks:
  - name: add ip
    shell: echo "host {{ database }} {{user}} {{ip}}/32 md5" >> /home/postgres/pgdata/data/pg_hba.conf
  - name: reload
    shell: /opt/pgsql/bin/pg_ctl -D /home/postgres/pgdata/data reload