---
- name: operate postgresql
  hosts: 
  remote_user: root
  vars:
    pg_port: 5432
    pg_host: 127.0.0.1
    src_database: 
    project: 
    date: "0207"
  tasks:
    - name: environment arguments
      copy: src=../roles/postgresql/files/.bash_profile dest=/root/.bash_profile

    - name: source
      shell: source /root/.bash_profile
      args:
        executable: /bin/bash

    - name: install dependents
      yum: name={{ item }}
      with_items:
       - python-psycopg2

    - name: create postgresql user
      postgresql_user: name={{ item.key }}  password={{ item.value }} login_host={{ pg_host }}
      with_items:
       - {key: "",value: ""}
      tags: user

    - name: create database
      postgresql_db: name={{ item }}_{{ project }}_{{ date }}  encoding='utf-8' owner={{ item }}_{{ project }} login_host={{ pg_host }}
      with_items:
       - uat
      tags: database

    - name: export data
      shell: /opt/pgsql/bin/pg_dump -d {{ src_database }} -U postgres -h {{ pg_host }} -f {{ src_database }}.sql
      args:
        executable: /bin/bash
      tags: export

    - name: import data
      shell: /opt/pgsql/bin/psql -U {{ item }}_{{ project }} {{ item }}_{{ project }}_{{ date }} -h {{ pg_host }} < {{ src_database }}.sql
      args:
        executable: /bin/bash
      with_items:
       - uat
      tags: import
