---
- name: operate postgresql
  hosts: 
  remote_user: root
  vars:
    pg_port: 5432
    pg_host: 127.0.0.1
    src_database: 
    project:
    date: 
    env:
      sit:
        password: 
      prod:
        password: 

  tasks:
#    - name: environment arguments
#      copy: src=../roles/postgresql/files/.bash_profile dest=/root/.bash_profile
#
#    - name: source
#      shell: source /root/.bash_profile
#      args:
#        executable: /bin/bash

    - name: install dependents
      yum: name={{ item }}
      with_items:
       - python-psycopg2

    - name: create postgresql user
      postgresql_user: name={{ project }}_{{ item.key }}  password={{ item.value.password }} login_host={{ pg_host }}
      with_dict: "{{ vars.env }}"
      tags: user

    - name: create database
      postgresql_db: name={{ project }}_{{ item.key }}_{{ date }}  encoding='utf-8' owner={{ project }}_{{ item.key }} login_host={{ pg_host }}
      with_dict: "{{ vars.env }}"
      tags: database

#    - name: export data
#      shell: /opt/pgsql/bin/pg_dump -d {{ src_database }} -U postgres -h {{ pg_host }} -f {{ src_database }}.{{ date }}.sql
#      args:
#        executable: /bin/bash
#      tags: export


#    - name: import data
#      shell: /opt/pgsql/bin/psql -U {{ item.key }}_{{ project }} {{ item.key }}_{{ project }}_{{ date }} -h {{ pg_host }} < {{ src_database }}.{{ date }}.sql
#      args:
#        executable: /bin/bash
#      with_dict: "{{ vars.env }}"
#      tags: import

    - name: add ip
      shell: echo "host {{ project }}_{{ item.key }}_{{ date }} {{ project }}_{{ item.key }} 0.0.0.0/0 md5" >> /home/postgres/pgdata/data/pg_hba.conf
      with_dict: "{{ vars.env }}"
      tags: hba

    - name: reload
      shell: su - postgres -c "/opt/pgsql/bin/pg_ctl -D /home/postgres/pgdata/data reload"
      tags: reload