---
# 用于批量添加公钥到服务器
- name: send ssh key
  hosts:
  remote_user: root
  tasks:
    - name: ssh-copy
      authorized_key: user=postgres key="{{ lookup('file', '/Users/user/.ssh/id_rsa.pub') }}"
      tags:
       - sshkey
