---
- name: send ssh key
  hosts: 
  remote_user: root
  tasks:
    - name: ssh-copy
      authorized_key: user=postgres key="{{ lookup('file', '/Users/atyun/.ssh/id_rsa.pub') }}"
      tags:
       - sshkey
