#- name: install influx repo
#  copy: src=influxdb.repo   dest=/etc/yum.repos.d/influxdb.repo
#
#- name: install software
#  yum: name={{item}} state=latest
#  with_items:
#    - telegraf

- name: install telegraf
  script: install_telegraf.sh >> telegraf_install_log.txt
  args:
    creates: telegraf_install_log.txt

- name: copy config
  template: src=telegraf.conf.j2 dest=/etc/telegraf/telegraf.conf

- name: start telegraf
  service: name=telegraf state=started enabled=yes
